# Generated by Django 4.2.25 on 2025-12-10 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('purpose', models.CharField(blank=True, max_length=180)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YieldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=120)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yield_qty', models.DecimalField(decimal_places=2, help_text='Total harvested (e.g., kg)', max_digits=10)),
                ('season', models.CharField(help_text='e.g., 2025 long rains', max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yield_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TraceabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=120)),
                ('batch_code', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traceability_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_label', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('crop', models.CharField(blank=True, max_length=120)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='soil_tests/')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nitrogen', models.DecimalField(blank=True, decimal_places=2, help_text='ppm', max_digits=6, null=True)),
                ('phosphorus', models.DecimalField(blank=True, decimal_places=2, help_text='ppm', max_digits=6, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, help_text='ppm', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soil_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD', 'Lead'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.farmergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
