# Generated by Django 4.2.25 on 2025-12-05 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(choices=[('SEEDS', 'Certified Seeds'), ('FERTILIZER', 'Fertilizer & Chemicals'), ('EQUIPMENT', 'Farm Equipment'), ('LABOR', 'Labor Costs'), ('OTHER', 'Other')], max_length=50)),
                ('repayment_period', models.IntegerField(help_text='Repayment period in months')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('MAIZE', 'Maize'), ('BEANS', 'Beans'), ('TEA', 'Tea'), ('COFFEE', 'Coffee')], max_length=50)),
                ('acreage', models.DecimalField(decimal_places=2, help_text='Size of land in acres', max_digits=5)),
                ('coverage_amount', models.DecimalField(decimal_places=2, help_text='Total value insured', max_digits=10)),
                ('premium_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Payment')], default='PENDING', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
