# Generated by Django 4.2.25 on 2025-12-10 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='tracking_note',
            field=models.TextField(blank=True),
        ),
    ]
